controller_list:
  - name: fake_manipulator_controller
    joints:
      - idr14050_joint_1_r
      - idr14050_joint_2_r
      - idr14050_joint_7_r
      - idr14050_joint_3_r
      - idr14050_joint_4_r
      - idr14050_joint_5_r
      - idr14050_joint_6_r
initial:  # Define initial robot poses.
  - group: manipulator
    pose: zero